# Site settings
title: Attack of the Stack
email: blah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  baseurl: '/wafflesblog'
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  CodeFluent
highlighter: pygments
encoding: UTF-8

# Build settings
markdown: kramdown
